# Generated by Django 5.2.4 on 2025-07-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_age', models.IntegerField(max_length=50)),
                ('patient_phone', models.IntegerField(max_length=15)),
                ('patient_email', models.CharField(max_length=20)),
            ],
        ),
    ]
