# Generated by Django 5.2.4 on 2025-07-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('token_no', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=100)),
                ('time', models.TimeField(max_length=50)),
            ],
        ),
    ]
