# Generated by Django 5.2.4 on 2025-07-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='date',
            field=models.DateField(max_length=50),
        ),
    ]
